{meta: title The Train Carrying Jimmie Rogers Home}
{meta: x_lyrics_source bluegrass-lyrics}
{meta: x_lyrics_url https://www.bluegrasslyrics.com/song/the-train-carrying-jimmie-rogers-home/}

{start_of_verse}
COME ALONG MY DEAR THE TIME IS DRAWING NEAR
WE’LL HAVE TO WALK DOWN WHERE THE FIELD IS OVERGROWN
CONSUMPTION CLAIMED HIS LIFE AND WE DARE NOT MISS THE SIGHT
OF THE TRAIN CARRYING JIMMIE ROGERS HOME
{end_of_verse}

{start_of_verse}
WE’VE HAD SOME HARD TIMES THESE PAST FEW YEARS
LOST THE FARM ALMOST LOST OUR SPIRITS TOO
BUT IT’S THE STRANGEST THING WHEN WE HEARD THAT MAN SING
OH WE KNEW SOMEHOW WE’D MAKE IT THROUGH
{end_of_verse}

{start_of_chorus}
I CAN HEAR THE WHISTLE BLOW THAT OL’ TRAIN IS GOING SLOW
SOUNDS LIKE IT’S CRYING FOR THE SINGING BRAKEMAN TOO
BACK TO THE SUNNY SOUTH HE’LL GO AND HE’LL NEVER ROAM NO MORE
HERE COMES THE TRAIN CARRYING JIMMIE ROGERS HOME
{end_of_chorus}

{start_of_verse}
COME HOME MY LITTLE SON AND LET ME HOLD YOU UP
I WANT YOU TO REMEMBER WHEN YOU ARE GROWN
HOW YOUR MAMA AND YOUR DAD WERE SO PROUD AND SO SAD
WATCHING THE TRAIN CARRYING JIMMIE ROGERS HOME
{end_of_verse}

