// Unit tests for the change gate — the authorization decision that says
// whether a user's edit lands ON somebody else's content or BESIDE it.
//
// Why these exist: until now `supabase/functions/` had no tests at all and CI
// never ran Deno, so `classifyChange` was verified by `deno check` (types) and
// nothing else. A privilege escalation was found and fixed in exactly this
// function — an unscoped ownership scan let contributing a banjo tab buy an
// in-place overwrite of a stranger's chart — and nothing stopped it regressing.
// The escalation regression is pinned explicitly below; search ESCALATION.
//
// Everything here is offline. `partBlocks` / `submittersOf` / `tabPartOwners`
// are pure. `classifyChange` reaches GitHub through `getFileContent`, so the
// tests swap `globalThis.fetch` for a fixture table (`withGithub`) — the real
// Contents-API decode path still runs, no socket does.
//
// Run: deno task test        (from the repo root)
//
// Fixtures in ./testdata/ are REAL work.yaml files copied out of works/, plus
// one generated by the real Python writer (how-long-blues) that both this
// suite and tests/test_ownership_parity.py answer questions about.

import {
  assertEquals,
  assertRejects,
} from "https://deno.land/std@0.168.0/testing/asserts.ts"

import {
  anyPartOwners,
  classifyChange,
  MetadataRefusedError,
  partBlocks,
  RATE_LIMIT_PER_HOUR,
  slugify,
  submissionsInLastHour,
  submittersOf,
  tabPartOwners,
} from "./pending-dispatch.ts"

// ============================================
// Fixtures
// ============================================

const fixture = (name: string) =>
  Deno.readTextFileSync(new URL(`./testdata/${name}`, import.meta.url))

/** Real: one chart (no submitter) + 8 tablature siblings, `composers:` AFTER `parts:`. */
const ANGELINE = fixture("angeline-the-baker.work.yaml")
/** Real: 8 tablature parts, several on the same instrument, no chart at all. */
const FOGGY = fixture("foggy-mountain-breakdown.work.yaml")
/** Real: chart only, with a `submitted_by`. */
const KING = fixture("king-of-california.work.yaml")
/** Real: hand-written — 2-space sequence indent, quoted scalars, flow `composers: [...]`. */
const BLUE_MOON = fixture("blue-moon-of-kentucky.work.yaml")
/** Generated by works_writer: primary chart + forked chart + tab, three owners. */
const HOW_LONG = fixture("how-long-blues.work.yaml")

const CASES = JSON.parse(fixture("ownership-cases.json")) as {
  work_yaml: string
  users: Record<string, string>
  cases: { user: string; part_type: string; owns: boolean; why: string }[]
}

const PRIMARY_CHART_OWNER = CASES.users.primary_chart_owner
const FORK_OWNER = CASES.users.fork_owner
const TAB_OWNER = CASES.users.tab_owner
const STRANGER = CASES.users.stranger

// ============================================
// GitHub stub
// ============================================

/** Base64 of a string's UTF-8 bytes — what the GitHub Contents API sends. */
function b64(text: string): string {
  let binary = ""
  for (const byte of new TextEncoder().encode(text)) {
    binary += String.fromCharCode(byte)
  }
  return btoa(binary)
}

/**
 * Run `fn` with `getFileContent` answering from `files` instead of the network.
 *
 * Keys are repo paths; a string value is the file's text, a number is an HTTP
 * status to return instead (404 = "no such work", 500 = a transient failure).
 * An unlisted path 404s.
 */
async function withGithub(
  files: Record<string, string | number>,
  fn: () => Promise<void>,
): Promise<void> {
  const real = globalThis.fetch
  globalThis.fetch = ((input: string | URL | Request) => {
    const url = String(input instanceof Request ? input.url : input)
    const path = decodeURIComponent(
      url.replace(/^.*\/contents\//, "").replace(/\?.*$/, ""),
    )
    const entry = files[path]
    if (entry === undefined) return Promise.resolve(new Response("", { status: 404 }))
    if (typeof entry === "number") {
      return Promise.resolve(new Response("boom", { status: entry }))
    }
    // Same shape the Contents API returns: base64 of the file's UTF-8 BYTES
    // in `.content`. (btoa() alone would reject any non-ASCII fixture, which
    // is exactly what the real API does not do.)
    return Promise.resolve(
      new Response(JSON.stringify({ content: b64(entry) }), { status: 200 }),
    )
  }) as typeof fetch
  try {
    await fn()
  } finally {
    globalThis.fetch = real
  }
}

const classify = (
  over: Partial<Parameters<typeof classifyChange>[0]> & { rowId: string; userId: string },
) =>
  classifyChange({
    trusted: false,
    githubToken: "test-token",
    ...over,
  })

// ============================================
// partBlocks — the YAML part-sequence splitter
// ============================================

Deno.test("partBlocks: real work.yaml — every block-sequence entry, dash flattened", () => {
  const blocks = partBlocks(ANGELINE)
  // 4 `tags:` entries + 9 parts + 1 `composers:` entry.
  assertEquals(blocks.length, 14)
  // The leading `- ` becomes two spaces, so every key inside reads as `key:`.
  assertEquals(blocks.some((b) => /^\s*-/.test(b)), false)
  assertEquals(blocks[4].startsWith("  type: lead-sheet"), true)
})

Deno.test("partBlocks: hand-written 2-space indent + quoted scalars still splits", () => {
  const blocks = partBlocks(BLUE_MOON)
  assertEquals(blocks.length, 1)
  // `composers: [Bill Monroe]` is flow style — it contributes no block.
  assertEquals(blocks[0].includes("Bill Monroe"), false)
  assertEquals(submittersOf(BLUE_MOON, "lead-sheet"), [])
})

Deno.test("partBlocks: a part block absorbs top-level keys that FOLLOW parts:", () => {
  // angeline-the-baker really does list `composers:` after `parts:`. The last
  // part's block therefore swallows the `composers:` line. That is fine — it
  // can only ADD lines to the last part, never move a key between two parts —
  // but pin it, because the day it stops being fine is the day someone puts an
  // identity-bearing top-level key after parts:.
  const last = partBlocks(ANGELINE).at(-1)!
  assertEquals(last.includes("Stephen Foster"), true)
  // ...and the part it belongs to is still read correctly.
  assertEquals(
    tabPartOwners(ANGELINE, "mandolin-3244.otf.json"),
    ["MandoTom2"],
  )
})

Deno.test("partBlocks: block-style tags:/composers: entries match nothing a caller looks for", () => {
  // They ARE blocks (bare scalars), but carry no `type:` and no `file:`.
  const blocks = partBlocks(ANGELINE)
  assertEquals(blocks.slice(0, 4).map((b) => b.trim()), [
    "Instrumental",
    "Scruggs",
    "Folk",
    // The last tag block absorbs the `parts:` key line — a block runs to the
    // next `- `, not to the end of its own mapping.
    "Bluegrass\nparts:",
  ])
  assertEquals(submittersOf(ANGELINE, "Instrumental"), [])
  assertEquals(tabPartOwners(ANGELINE, "Bluegrass"), null)
})

Deno.test("partBlocks: a nested sequence inside provenance splits the part (under-count, safe)", () => {
  const yaml = `id: nested
parts:
- type: lead-sheet
  file: lead-sheet.pro
  provenance:
    source: user-submission
    contributors:
      - ${STRANGER}
    submitted_by: ${PRIMARY_CHART_OWNER}
`
  // The nested `- ` starts a new block, so the part's own submitted_by is
  // orphaned into a block with no `type:`.
  assertEquals(partBlocks(yaml).length, 2)
  // Consequence: the real owner loses ownership and their next edit FORKS.
  // Annoying, not dangerous — and nobody else gains anything.
  assertEquals(submittersOf(yaml, "lead-sheet"), [])
})

Deno.test("partBlocks: CRLF line endings", () => {
  const yaml = KING.replace(/\n/g, "\r\n")
  assertEquals(partBlocks(yaml).length, partBlocks(KING).length)
  assertEquals(submittersOf(yaml, "lead-sheet"), ["github:Jollyhrothgar"])
})

Deno.test("partBlocks: a flow-style part contributes a block nothing can read", () => {
  const yaml = `parts:
- {type: lead-sheet, file: lead-sheet.pro, provenance: {submitted_by: ${STRANGER}}}
`
  assertEquals(partBlocks(yaml).length, 1)
  assertEquals(submittersOf(yaml, "lead-sheet"), [])
  assertEquals(tabPartOwners(yaml, "lead-sheet.pro"), null)
})

Deno.test("partBlocks: an empty parts list yields nothing", () => {
  assertEquals(partBlocks("id: x\ntitle: X\nparts: []\n"), [])
  assertEquals(partBlocks(""), [])
  assertEquals(submittersOf("", "lead-sheet"), [])
})

// ============================================
// partBlocks — the "mis-splits bias safe" claim
// ============================================
//
// The claim under test: when partBlocks mis-splits, it UNDER-counts ownership,
// which yields `fork`/`add` (additive) rather than `update` (destructive).
//
// It holds for every shape above. It does NOT hold universally — see the bare
// `-` case below.

Deno.test("partBlocks: a bare `-` sequence entry still opens a new part", () => {
  // REGRESSION. `-` alone on a line, with the entry's keys on the following
  // lines, is valid YAML and a common hand-editing style. The splitter used
  // to require `-` followed by whitespace (/^\s*-\s/), so a bare `-` did not
  // open a block and part B's lines were appended to part A's.
  //
  // That merge was an OVER-count, and in the destructive direction. blockValue
  // takes the first match of each key, so the merged block answered with part
  // A's `type:` and part B's `submitted_by:` — an imported chart followed by
  // the caller's own tab read as "the caller submitted a LEAD SHEET here",
  // which is an in-place edit right over somebody else's chart. The exact
  // escalation the type scoping closes, reached through whitespace instead.
  //
  // Nothing in the pipeline emits this style (works_writer uses PyYAML's
  // `- key: value`), so it is not submitter-reachable — but `works/` is the
  // hand-editable store by design, so that is not a defence.
  const yaml = `id: angeline-the-baker
title: Angeline the Baker
parts:
- type: lead-sheet
  format: chordpro
  file: lead-sheet.pro
  default: true
  provenance:
    source: tunearch
    imported_at: '2026-07-26'
-
  type: tablature
  instrument: banjo
  format: otf
  file: banjo.otf.json
  provenance:
    source: user-submission
    submitted_by: ${STRANGER}
`
  assertEquals(partBlocks(yaml).length, 2)
  // The tab submitter owns the tab and NOT the chart.
  assertEquals(submittersOf(yaml, "lead-sheet"), [])
  assertEquals(submittersOf(yaml, "tablature"), [STRANGER])
  assertEquals(tabPartOwners(yaml, "banjo.otf.json"), [STRANGER])
})

Deno.test("partBlocks: a `---` document marker does not start a block", () => {
  const yaml = `---
id: x
parts:
- type: lead-sheet
  file: lead-sheet.pro
  provenance:
    submitted_by: ${PRIMARY_CHART_OWNER}
`
  assertEquals(partBlocks(yaml).length, 1)
  assertEquals(submittersOf(yaml, "lead-sheet"), [PRIMARY_CHART_OWNER])
})

// ============================================
// submittersOf — scoped to ONE part type
// ============================================

Deno.test("submittersOf: counts only parts of the named type", () => {
  assertEquals(submittersOf(HOW_LONG, "lead-sheet"), [PRIMARY_CHART_OWNER, FORK_OWNER])
  assertEquals(submittersOf(HOW_LONG, "tablature"), [TAB_OWNER])
})

Deno.test("submittersOf: the tab owner is NOT a chart submitter (the escalation, at unit level)", () => {
  assertEquals(submittersOf(HOW_LONG, "lead-sheet").includes(TAB_OWNER), false)
  assertEquals(submittersOf(HOW_LONG, "tablature").includes(PRIMARY_CHART_OWNER), false)
})

Deno.test("submittersOf: imported works name nobody", () => {
  assertEquals(submittersOf(ANGELINE, "lead-sheet"), [])
  assertEquals(submittersOf(ANGELINE, "tablature"), [])
  assertEquals(submittersOf(FOGGY, "tablature"), [])
  assertEquals(submittersOf(FOGGY, "lead-sheet"), [])
})

Deno.test("submittersOf: a non-uuid submitter (github: handle) is carried through verbatim", () => {
  assertEquals(submittersOf(KING, "lead-sheet"), ["github:Jollyhrothgar"])
})

Deno.test("submittersOf: shared parity table (mirrors process_pending.owns_content)", () => {
  assertEquals(CASES.work_yaml, "how-long-blues.work.yaml")
  for (const c of CASES.cases) {
    const uid = CASES.users[c.user]
    assertEquals(
      submittersOf(HOW_LONG, c.part_type).includes(uid),
      c.owns,
      `${c.user} / ${c.part_type}: ${c.why}`,
    )
  }
})

// ============================================
// tabPartOwners — null vs [] vs somebody
// ============================================

Deno.test("tabPartOwners: null when NO part names the file", () => {
  assertEquals(tabPartOwners(ANGELINE, "dobro.otf.json"), null)
  assertEquals(tabPartOwners(FOGGY, "banjo-99999.otf.json"), null)
})

Deno.test("tabPartOwners: null when a NON-tablature part names the file", () => {
  // "the client is talking about a file that isn't a published tab" — a
  // different answer from "it's somebody's tab", on purpose.
  assertEquals(tabPartOwners(HOW_LONG, "lead-sheet.pro"), null)
  assertEquals(tabPartOwners(HOW_LONG, "lead-sheet-simplified.pro"), null)
})

Deno.test("tabPartOwners: submitted_by counts", () => {
  assertEquals(tabPartOwners(HOW_LONG, "banjo.otf.json"), [TAB_OWNER])
})

Deno.test("tabPartOwners: author counts too (the retired PR flow and every import)", () => {
  assertEquals(tabPartOwners(FOGGY, "banjo.otf.json"), ["schlange"])
  assertEquals(tabPartOwners(FOGGY, "banjo-24054.otf.json"), ["corcoran"])
  assertEquals(tabPartOwners(ANGELINE, "banjo-19887.otf.json"), ["Tim Purcell"])
})

Deno.test("tabPartOwners: distinguishes siblings on the same instrument", () => {
  // foggy-mountain-breakdown carries several banjo takes; owning one is not
  // owning the next.
  assertEquals(tabPartOwners(FOGGY, "banjo-22352.otf.json"), ["HOWDYDOODY"])
  assertEquals(tabPartOwners(FOGGY, "banjo-24054.otf.json"), ["corcoran"])
})

Deno.test("tabPartOwners: both identity fields, in order", () => {
  const yaml = `parts:
- type: tablature
  file: banjo.otf.json
  provenance:
    submitted_by: ${TAB_OWNER}
    author: schlange
`
  assertEquals(tabPartOwners(yaml, "banjo.otf.json"), [TAB_OWNER, "schlange"])
})

Deno.test("tabPartOwners: [] when a tab part names the file but nobody is recorded", () => {
  const yaml = `parts:
- type: tablature
  file: banjo.otf.json
  provenance:
    source: banjo-hangout
`
  // Empty list, not null: the file IS published, it just has no owner on
  // record — so a non-trusted caller lands `add`, never `update`.
  assertEquals(tabPartOwners(yaml, "banjo.otf.json"), [])
})

Deno.test("tabPartOwners: an apostrophe in a name reads as no owner (safe direction)", () => {
  // blockValue's value pattern excludes quote characters, so `author: O'Brien`
  // does not parse. It matters only for `author`, which is a display name a
  // uuid could never equal anyway — the outcome is `add` either way.
  const yaml = `parts:
- type: tablature
  file: banjo.otf.json
  provenance:
    author: O'Brien
`
  assertEquals(tabPartOwners(yaml, "banjo.otf.json"), [])
})

Deno.test("tabPartOwners: quoted and whitespace-padded filenames", () => {
  const yaml = `parts:
- type: tablature
  file: 'banjo-2.otf.json'
  provenance:
    submitted_by: ${TAB_OWNER}
- type: tablature
  file: "fiddle.otf.json"
  provenance:
    submitted_by: ${STRANGER}
`
  assertEquals(tabPartOwners(yaml, "banjo-2.otf.json"), [TAB_OWNER])
  assertEquals(tabPartOwners(yaml, "  fiddle.otf.json  "), [STRANGER])
})

// ============================================
// classifyChange — lead sheet
// ============================================

Deno.test("classifyChange lead-sheet: no work at the target -> create", async () => {
  await withGithub({}, async () => {
    const out = await classify({ rowId: "brand-new-song", userId: STRANGER })
    assertEquals(out.mode, "create")
  })
})

Deno.test("classifyChange lead-sheet: caller submitted a chart here -> update", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    for (const uid of [PRIMARY_CHART_OWNER, FORK_OWNER]) {
      const out = await classify({
        rowId: "row-1",
        replacesId: "how-long-blues",
        userId: uid,
      })
      assertEquals(out.mode, "update")
      assertEquals(out.workId, "how-long-blues")
    }
  })
})

Deno.test("classifyChange lead-sheet: trusted non-owner -> update", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: STRANGER,
      trusted: true,
    })
    assertEquals(out.mode, "update")
    assertEquals(out.reason, "trusted user in-place edit")
  })
})

Deno.test("classifyChange lead-sheet: anyone else -> fork", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: STRANGER,
    })
    assertEquals(out.mode, "fork")
    assertEquals(out.workId, "how-long-blues")
  })
})

Deno.test("classifyChange lead-sheet: an imported chart nobody submitted -> fork", async () => {
  await withGithub({ "works/angeline-the-baker/work.yaml": ANGELINE }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "angeline-the-baker",
      userId: STRANGER,
    })
    assertEquals(out.mode, "fork")
  })
})

Deno.test("classifyChange lead-sheet: absent/odd part_type falls into the chart column", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    for (const partType of [undefined, null, "lead-sheet", "abc-notation"]) {
      const out = await classify({
        rowId: "row-1",
        replacesId: "how-long-blues",
        userId: TAB_OWNER,
        partType,
      })
      // Never `add` (that is the tab column) and never `update` — TAB_OWNER
      // owns no chart here.
      assertEquals(out.mode, "fork", `part_type=${partType}`)
    }
  })
})

// ============================================
// ESCALATION REGRESSION
// ============================================

Deno.test("ESCALATION: owning only a TAB must not confer update over the chart", async () => {
  // The bug that was found and fixed: `submitted_by` used to be scanned over
  // the flat file, so "Alice submitted a banjo tab here" read as "Alice owns
  // content here" -> update -> an in-place overwrite of a stranger's lyrics,
  // and the work's title/artist/key along with them.
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "lead-sheet",
    })
    assertEquals(out.mode, "fork")
    assertEquals(out.reason, "edit of another contributor's content")
  })
})

Deno.test("ESCALATION (mirror): owning only a CHART must not confer update over a tab", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    for (const uid of [PRIMARY_CHART_OWNER, FORK_OWNER]) {
      const out = await classify({
        rowId: "row-1",
        replacesId: "how-long-blues",
        userId: uid,
        partType: "tablature",
        partFile: "banjo.otf.json",
      })
      assertEquals(out.mode, "add")
      assertEquals(out.workId, "how-long-blues")
    }
  })
})

// ============================================
// classifyChange — tablature
// ============================================

Deno.test("classifyChange tablature: no work at the target -> create, slug from the TITLE", async () => {
  // A tab row's id is synthetic (`tab:<slug>:<rand>`) because two people must
  // be able to tab the same song without colliding on the pending_songs PK.
  // So a tab that mints a work names it from the title, never from the row id.
  // (ID-SCHEME DEPENDENT — see the report.)
  await withGithub({}, async () => {
    const out = await classify({
      rowId: "tab:salt-creek:9f3c",
      title: "Salt Creek",
      userId: STRANGER,
      partType: "tablature",
      partFile: null,
    })
    assertEquals(out.mode, "create")
    assertEquals(out.workId, "salt-creek")
  })
})

Deno.test("classifyChange tablature: a titleless tab with no target throws rather than guessing", async () => {
  await withGithub({}, async () => {
    await assertRejects(
      () =>
        classify({
          rowId: "tab:salt-creek:9f3c",
          title: "   ",
          userId: STRANGER,
          partType: "tablature",
        }),
      Error,
      "no target work id",
    )
  })
})

Deno.test("classifyChange tablature: replaces_id beats the title when both are present", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "tab:something-else:9f3c",
      title: "Something Else Entirely",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "tablature",
      partFile: "banjo.otf.json",
    })
    assertEquals(out.mode, "update")
    assertEquals(out.workId, "how-long-blues")
  })
})

Deno.test("slugify: same rule as work_schema.slugify in Python", () => {
  assertEquals(slugify("Salt Creek"), "salt-creek")
  assertEquals(slugify("  Blue Moon of Kentucky  "), "blue-moon-of-kentucky")
  assertEquals(slugify("Cripple Creek (Clawhammer)"), "cripple-creek-clawhammer")
  assertEquals(slugify("Éirinn go Brách"), "eirinn-go-brach")
  assertEquals(slugify("I'm Working on a Building"), "i-m-working-on-a-building")
  assertEquals(slugify("---"), "")
  assertEquals(slugify(""), "")
})

Deno.test("classifyChange tablature: no part_file is a submission, not a correction -> add", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    for (const partFile of [undefined, null, "", "   "]) {
      const out = await classify({
        rowId: "row-1",
        replacesId: "how-long-blues",
        userId: TAB_OWNER,
        partType: "tablature",
        partFile,
      })
      assertEquals(out.mode, "add", `part_file=${JSON.stringify(partFile)}`)
    }
  })
})

Deno.test("classifyChange tablature: even a TRUSTED caller with no part_file -> add", async () => {
  // There is no file to own yet, so trust cannot promote it to a rewrite.
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: STRANGER,
      trusted: true,
      partType: "tablature",
    })
    assertEquals(out.mode, "add")
  })
})

Deno.test("classifyChange tablature: part_file nobody publishes -> add", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "tablature",
      partFile: "dobro.otf.json",
      trusted: true,
    })
    // Even trusted: an unknown file is not an in-place edit of anything.
    assertEquals(out.mode, "add")
  })
})

Deno.test("classifyChange tablature: caller owns the named part -> update", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "tablature",
      partFile: "banjo.otf.json",
    })
    assertEquals(out.mode, "update")
    assertEquals(out.reason, "caller submitted this tab")
  })
})

Deno.test("classifyChange tablature: trusted caller, someone else's part -> update", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: STRANGER,
      trusted: true,
      partType: "tablature",
      partFile: "banjo.otf.json",
    })
    assertEquals(out.mode, "update")
    assertEquals(out.reason, "trusted user in-place edit")
  })
})

Deno.test("classifyChange tablature: untrusted correction to another's tab -> add", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: STRANGER,
      partType: "tablature",
      partFile: "banjo.otf.json",
    })
    assertEquals(out.mode, "add")
  })
})

Deno.test("classifyChange tablature: owning ONE banjo take is not owning the sibling", async () => {
  // foggy-mountain-breakdown carries eight tabs by different people.
  await withGithub({ "works/foggy-mountain-breakdown/work.yaml": FOGGY }, async () => {
    const mine = await classify({
      rowId: "row-1",
      replacesId: "foggy-mountain-breakdown",
      userId: "schlange",
      partType: "tablature",
      partFile: "banjo.otf.json",
    })
    assertEquals(mine.mode, "update")

    const theirs = await classify({
      rowId: "row-1",
      replacesId: "foggy-mountain-breakdown",
      userId: "schlange",
      partType: "tablature",
      partFile: "banjo-24054.otf.json",
    })
    assertEquals(theirs.mode, "add")
  })
})

Deno.test("classifyChange tablature: a part_file pointing at a CHART -> add", async () => {
  // A client claiming `part_file: lead-sheet.pro` on a tab row must not reach
  // the chart through the tab column.
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: PRIMARY_CHART_OWNER,
      partType: "tablature",
      partFile: "lead-sheet.pro",
    })
    assertEquals(out.mode, "add")
  })
})

// ============================================
// anyPartOwners — the metadata column's LOOSER question
// ============================================
//
// Deliberately a different question from submittersOf, and the tests are here
// to stop a later reader "fixing" one into the other. submittersOf answers
// "may you rewrite content of this kind in place?" and MUST stay scoped per
// part type. This answers "do you have any stake in this work at all?" and is
// only ever used to decide whether you may edit the work's own title / artist
// / key / notes — where nobody's content is touched.

Deno.test("anyPartOwners: everyone who contributed a part, of any kind", () => {
  assertEquals(anyPartOwners(HOW_LONG), [PRIMARY_CHART_OWNER, FORK_OWNER, TAB_OWNER])
})

Deno.test("anyPartOwners: the tab owner IS here (this is the whole difference)", () => {
  // submittersOf(HOW_LONG, 'lead-sheet') excludes TAB_OWNER — that exclusion
  // is the escalation fix. This one includes them, on purpose.
  assertEquals(submittersOf(HOW_LONG, "lead-sheet").includes(TAB_OWNER), false)
  assertEquals(anyPartOwners(HOW_LONG).includes(TAB_OWNER), true)
})

Deno.test("anyPartOwners: a stranger is still a stranger", () => {
  assertEquals(anyPartOwners(HOW_LONG).includes(STRANGER), false)
})

Deno.test("anyPartOwners: `author` counts on tablature parts (imports and the retired PR flow)", () => {
  assertEquals(anyPartOwners(FOGGY).includes("schlange"), true)
  assertEquals(anyPartOwners(ANGELINE).includes("Tim Purcell"), true)
})

Deno.test("anyPartOwners: `author` does NOT count on a chart part", () => {
  // `author` is the tablature vocabulary — a display name credited on a tab.
  // A chart's contributor is `submitted_by` (a verified uuid), and honouring
  // a hand-written `author:` on a lead sheet would let an arbitrary string in
  // a scraped work.yaml name an owner.
  const yaml = `parts:
- type: lead-sheet
  file: lead-sheet.pro
  provenance:
    source: classic-country
    author: ${STRANGER}
`
  assertEquals(anyPartOwners(yaml), [])
})

Deno.test("anyPartOwners: a block with no `type:` is not a part", () => {
  // tags:/composers: entries are block-sequence entries too.
  assertEquals(anyPartOwners(BLUE_MOON), [])
  assertEquals(anyPartOwners(""), [])
  assertEquals(anyPartOwners("id: x\nparts: []\n"), [])
})

// ============================================
// classifyChange — metadata
// ============================================

Deno.test("classifyChange metadata: owning ANY part earns the edit", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    for (const uid of [PRIMARY_CHART_OWNER, FORK_OWNER, TAB_OWNER]) {
      const out = await classify({
        rowId: "meta:how-long-blues:9f3c2a",
        replacesId: "how-long-blues",
        userId: uid,
        partType: "metadata",
      })
      assertEquals(out.mode, "metadata")
      assertEquals(out.workId, "how-long-blues")
      assertEquals(out.reason, "caller contributed a part of this work")
    }
  })
})

Deno.test("classifyChange metadata: owning only a TAB earns it — unlike a chart edit", async () => {
  // The deliberate asymmetry, pinned side by side so the two questions can't
  // be quietly merged. Same user, same work, two different asks:
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const chartEdit = await classify({
      rowId: "row-1",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "lead-sheet",
    })
    // Rewriting somebody's lyrics: no. It forks.
    assertEquals(chartEdit.mode, "fork")

    const metadataEdit = await classify({
      rowId: "meta:how-long-blues:9f3c2a",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "metadata",
    })
    // Saying the song is by the Stanley Brothers: yes. Nothing is rewritten.
    assertEquals(metadataEdit.mode, "metadata")
  })
})

Deno.test("classifyChange metadata: a trusted non-contributor -> metadata", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "meta:how-long-blues:9f3c2a",
      replacesId: "how-long-blues",
      userId: STRANGER,
      trusted: true,
      partType: "metadata",
    })
    assertEquals(out.mode, "metadata")
    assertEquals(out.reason, "trusted user metadata edit")
  })
})

Deno.test("REFUSAL: a non-contributor's metadata edit is refused, never forked", async () => {
  // The one column with no additive fallback. A second opinion about the
  // artist is not an arrangement, so silently forking it would put a
  // duplicate work in the corpus every time somebody fixed a typo they were
  // not entitled to fix.
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const error = await assertRejects(
      () =>
        classify({
          rowId: "meta:how-long-blues:9f3c2a",
          replacesId: "how-long-blues",
          userId: STRANGER,
          partType: "metadata",
        }),
      MetadataRefusedError,
    )
    assertEquals(error.status, 403)
    assertEquals(error.workId, "how-long-blues")
  })
})

Deno.test("REFUSAL: an imported work nobody submitted refuses everyone untrusted", async () => {
  // angeline-the-baker has no `submitted_by` anywhere — its tabs carry
  // Hangout display names. A uuid never equals one, so no logged-in user
  // owns a part here and only trust opens it.
  await withGithub({ "works/angeline-the-baker/work.yaml": ANGELINE }, async () => {
    await assertRejects(
      () =>
        classify({
          rowId: "meta:angeline-the-baker:9f3c2a",
          replacesId: "angeline-the-baker",
          userId: STRANGER,
          partType: "metadata",
        }),
      MetadataRefusedError,
    )
    const trusted = await classify({
      rowId: "meta:angeline-the-baker:9f3c2a",
      replacesId: "angeline-the-baker",
      userId: STRANGER,
      trusted: true,
      partType: "metadata",
    })
    assertEquals(trusted.mode, "metadata")
  })
})

Deno.test("REFUSAL: no work at the target is a 404, not a create", async () => {
  // A metadata row has no content to seed a work from, so `create` is not one
  // of its modes. Falling through to create would mint an empty work out of a
  // typo'd slug.
  await withGithub({}, async () => {
    const error = await assertRejects(
      () =>
        classify({
          rowId: "meta:nope:9f3c2a",
          replacesId: "no-such-work",
          userId: STRANGER,
          trusted: true,
          partType: "metadata",
        }),
      MetadataRefusedError,
    )
    assertEquals(error.status, 404)
  })
})

Deno.test("REFUSAL: a metadata row with no target is a 400, and never reads the row id", async () => {
  // `meta:<slug>:<rand>` is a pending_songs primary key, not a work slug. The
  // chart column falls back to the row id; this one must not, or the id
  // itself would become a directory name.
  await withGithub({ "works/meta:how-long-blues:9f3c2a/work.yaml": HOW_LONG }, async () => {
    for (const replacesId of [undefined, null, "", "   "]) {
      const error = await assertRejects(
        () =>
          classify({
            rowId: "meta:how-long-blues:9f3c2a",
            replacesId,
            userId: PRIMARY_CHART_OWNER,
            trusted: true,
            partType: "metadata",
          }),
        MetadataRefusedError,
      )
      assertEquals(error.status, 400, `replacesId=${JSON.stringify(replacesId)}`)
    }
  })
})

Deno.test("classifyChange metadata: part_file is ignored — this column edits no part", async () => {
  await withGithub({ "works/how-long-blues/work.yaml": HOW_LONG }, async () => {
    const out = await classify({
      rowId: "meta:how-long-blues:9f3c2a",
      replacesId: "how-long-blues",
      userId: TAB_OWNER,
      partType: "metadata",
      partFile: "lead-sheet.pro",
    })
    assertEquals(out.mode, "metadata")
  })
})

// ============================================
// classifyChange — targeting and failure modes
// ============================================

Deno.test("classifyChange: replaces_id picks the work; without it the row id does", async () => {
  await withGithub(
    {
      "works/how-long-blues/work.yaml": HOW_LONG,
      "works/king-of-california/work.yaml": KING,
    },
    async () => {
      const viaReplaces = await classify({
        rowId: "some-row",
        replacesId: "how-long-blues",
        userId: PRIMARY_CHART_OWNER,
      })
      assertEquals(viaReplaces.workId, "how-long-blues")

      const viaRowId = await classify({
        rowId: "king-of-california",
        userId: "github:Jollyhrothgar",
      })
      assertEquals(viaRowId.workId, "king-of-california")
      assertEquals(viaRowId.mode, "update")
    },
  )
})

Deno.test("classifyChange: a transient GitHub failure throws, never reads as 'no work'", async () => {
  // The dangerous misread: 500 -> null -> `create` -> a real work.yaml
  // replaced by a placeholder. getFileContent only returns null on a real 404.
  for (const status of [401, 403, 500, 502]) {
    await withGithub({ "works/how-long-blues/work.yaml": status }, async () => {
      await assertRejects(
        () =>
          classify({
            rowId: "row-1",
            replacesId: "how-long-blues",
            userId: STRANGER,
          }),
        Error,
        String(status),
      )
    })
  }
})

// ============================================
// submissionsInLastHour — the durable rate limit
// ============================================

/** Minimal stand-in for the bits of SupabaseClient this function touches. */
// deno-lint-ignore no-explicit-any
function fakeAdmin(result: { count?: number | null; error?: { message: string } }): any {
  const chain = {
    select: () => chain,
    eq: () => chain,
    gte: () => Promise.resolve(result),
  }
  return { from: () => chain }
}

Deno.test("submissionsInLastHour: returns the counted rows", async () => {
  assertEquals(await submissionsInLastHour(fakeAdmin({ count: 7 }), "u"), 7)
  assertEquals(await submissionsInLastHour(fakeAdmin({ count: 0 }), "u"), 0)
  assertEquals(await submissionsInLastHour(fakeAdmin({ count: null }), "u"), 0)
})

Deno.test("submissionsInLastHour: fails OPEN when the count errors", async () => {
  // Deliberate: a hiccuping SELECT must not lock everyone out of contributing.
  // Size caps and RLS are still in force.
  const n = await submissionsInLastHour(fakeAdmin({ error: { message: "boom" } }), "u")
  assertEquals(n, 0)
  assertEquals(n < RATE_LIMIT_PER_HOUR, true)
})
