#!/usr/bin/env python3
"""Generate the golden-diff fixture for the in-browser TEF parser.

For every V2 .tef in sources/banjo-hangout/downloads/ and in
tests/parser/fixtures/ (the small, checked-in, deliberately curated set —
so format sub-variants stay covered even when the gitignored corpus is
absent), dump:
  - the raw bytes (base64) — so the JS test is self-contained (no gitignored
    binaries needed in CI)
  - the reference OTF document (Python tef_to_otf(...).to_dict())

The JS gate (docs/js/__tests__/tef-import-golden.test.js) decodes the bytes,
runs parseTef(), and asserts canonical-JSON equality against the OTF here.

Regenerate whenever the Python parser legitimately changes:
  uv run python docs/js/tef-import/__fixtures__/gen_golden.py

Full regeneration rewrites the entry set to whatever .tef files happen to be
on disk. When a parser change affects only known files (or adds one), refresh
just those and leave the rest of the fixture alone:

  uv run python docs/js/tef-import/__fixtures__/gen_golden.py \
      --only 10591_fire_on_the_mountain_v2_4byte.tef

Output: docs/js/tef-import/__fixtures__/golden.json
"""
import argparse
import base64
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO / "sources" / "banjo-hangout" / "src"))

from tef_parser.reader import TEFReader  # noqa: E402
from tef_parser.otf import tef_to_otf     # noqa: E402

DOWNLOADS = REPO / "sources" / "banjo-hangout" / "downloads"
CURATED = REPO / "tests" / "parser" / "fixtures"
OUT = Path(__file__).resolve().parent / "golden.json"


def source_files() -> list[Path]:
    """Every candidate .tef, curated fixtures last so they win on name clash."""
    return sorted(DOWNLOADS.glob("*.tef")) + sorted(CURATED.glob("*.tef"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--only", nargs="+", metavar="NAME",
        help="refresh only these .tef file names, merging into the existing "
             "fixture instead of rewriting the whole entry set")
    args = ap.parse_args()

    fixture = {"_note": "Generated by gen_golden.py — do not hand-edit.", "files": {}}
    if args.only:
        if not OUT.exists():
            print("--only needs an existing golden.json", file=sys.stderr)
            return 1
        fixture = json.loads(OUT.read_text())

    ok = skipped = errored = 0
    for f in source_files():
        if args.only and f.name not in args.only:
            continue
        raw = f.read_bytes()
        try:
            reader = TEFReader(str(f))
            tef = reader.parse()          # both V2 and V3
            otf = tef_to_otf(tef).to_dict()
        except Exception as exc:  # noqa: BLE001
            # The browser parser is expected to skip the same files (e.g. a V3
            # sub-variant without the 'debt' marker → empty notation). Record
            # them as skips, not fixtures.
            skipped += 1
            print(f"  skip {f.name}: {type(exc).__name__}: {exc}", file=sys.stderr)
            continue
        # A file that parses to zero notes is a skip on both sides.
        if not any(otf.get("notation", {}).values()):
            skipped += 1
            print(f"  skip {f.name}: empty notation", file=sys.stderr)
            continue
        fixture["files"][f.name] = {
            "bytes_b64": base64.b64encode(raw).decode("ascii"),
            "otf": otf,
        }
        ok += 1

    OUT.write_text(json.dumps(fixture, sort_keys=True))
    print(f"Wrote {OUT.relative_to(REPO)}: {ok} files "
          f"({skipped} skipped, {errored} errored), "
          f"{OUT.stat().st_size // 1024}KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
