{meta: title Hang Your Head in Shame}
{meta: artist Bob Wills}
{meta: composer Fred Rose, Ed G. Nelson, Steve Nelson}

{start_of_verse: Verse 1}
[C]DON'T YOUR CONSCIENCE EVER BOTHER [F]YOU
[C]EVERY TIME YOU HEAR MY [G7]NAME
[C]TRY AND THINK OF ALL THAT I'VE BEEN [F]THROUGH
AND [C]HANG YOUR [G7]HEAD IN [C]SHAME
{end_of_verse}

{start_of_verse: Verse 2}
[F]SOMEONE CAME ALONG AND TOOK MY [C]PLACE 
THEN YOU GAVE ME ALL THE [G7]BLAME
[C]YOU SHOULD GO SOMEWHERE AND HIDE YOUR [F]FACE
AND [C]HANG YOUR [G7]HEAD IN [C]SHAME
{end_of_verse}

{start_of_verse: Verse 3}
NOW THAT YOU HAVE GONE IT'S PLAIN TO [F]SEE
[C]TRUE LOVE NEVER WAS YOUR [G7]AIM
[C]REALIZE HOW MEAN YOU WERE TO [F]ME
AND [C]HANG YOUR [G7]HEAD IN [C]SHAME
{end_of_verse}

{start_of_verse: Verse 4}
I SHOULD HATE YOU BUT I LOVE YOU [F]STILL
[C]IN MY HEART I'VE KEPT THE [G7]FLAME
[C]YOU'LL BE SORRY DARLING YES YOU [F]WILL
AND [C]HANG YOUR [G7]HEAD IN [C]SHAME
{end_of_verse}

{start_of_verse: Verse 5}
[F]SOMEONE CAME ALONG AND TOOK MY [C]PLACE 
THEN YOU GAVE ME ALL THE [G7]BLAME
[C]YOU SHOULD GO SOMEWHERE AND HIDE YOUR [F]FACE
AND [C]HANG YOUR [G7]HEAD IN [C]SHAME
{end_of_verse}
