{meta: title Just When I Needed You}
{meta: artist George Jones}
{meta: composer Johnny Wright, Jack Anglin, Clyde Baum}

{start_of_verse: Verse 1}
[C]JUST WHEN I NEEDED YOU  YOU LEFT AND WENT [F]AWAY
[C]YOU MADE MY LIFE SO BLUE BOTH NIGHT AND [G7]DAY
[C]YOU LEFT ME HERE BEHIND WITH A TROUBLED WORRIED [F]MIND
[C]SO BROKEN HEARTED [G7]TOO  JUST WHEN I NEEDED [C]YOU
{end_of_verse}

{start_of_verse: Verse 2}
[F]I CRIED  I CRIED  I PRAYED LORD  I TRIED TO FORGET [C]YOU
[G7]AND NEVER CALL YOUR NAME  WHAT A SHAME  WHAT A [C]SHAME
[F]YOU'RE THE ONE WHO WAS TO [C]BLAME
[F]YOU'RE THE ONE WHO [C]WAS UNTRUE [G7]JUST WHEN I NEEDED [C]YOU
{end_of_verse}

{start_of_verse: Verse 3}
[F]YOU SAID IT'S BEST WE PART AND NEVER LOVE AGAIN
[C]AND 'THO IT BROKE MY HEART  I WON'T [G7]COMPLAIN
[C]YOU KNOW I LOVE YOU STILL AND DEAR I ALWAYS [F]WILL
[C]ALTHOUGH YOU PROVED [G7]UNTRUE JUST WHEN I NEEDED [C]YOU
{end_of_verse}

{start_of_verse: Verse 4}
[F]I CRIED  I CRIED  I PRAYED LORD  I TRIED TO FORGET [C]YOU
[G7]AND NEVER CALL YOUR NAME  WHAT A SHAME  WHAT A [C]SHAME
[F]YOU'RE THE ONE WHO WAS TO [C]BLAME
[F]YOU'RE THE ONE WHO [C]WAS UNTRUE [G7]JUST WHEN I NEEDED [C]YOU
{end_of_verse}
